# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
inhibit_all_warnings!

target 'RxBus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxBus
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya/RxSwift'
  pod 'XMLParsing', :git => 'https://github.com/ShawnMoore/XMLParsing.git'
end
